if not(GetLocale() == "esES") then
    return;
end

local L = WeakAuras.L

-- Options translation
-- L[""] = ""
L["1 Match"] = "1 Correspondencia"
-- L["A 20x20 pixels icon"] = ""
-- L["A 32x32 pixels icon"] = ""
-- L["A 40x40 pixels icon"] = ""
-- L["A 48x48 pixels icon"] = ""
-- L["A 64x64 pixels icon"] = ""
L["Actions"] = "Acciones"
L["Activate when the given aura(s) |cFFFF0000can't|r be found"] = "Activar cuando el/las aura(s) |cFFFF0000no|r se encontraron"
L["Addons"] = "Addons"
L["Add to new Dynamic Group"] = "Añadir al nuevo Grupo Dinámico"
L["Add to new Group"] = "Añadir al nuevo Grupo"
L["Add Trigger"] = "Añadir Disparador"
L["A group that dynamically controls the positioning of its children"] = "Un grupo que dinámicamente controla la posición de sus hijos"
L["Align"] = "Alinear"
L["Allow Full Rotation"] = "Permitir Rotación Total"
L["Alpha"] = "Transparencia"
L["Anchor"] = "Anclaje"
L["Anchor Point"] = "Punto de Anclaje"
L["Angle"] = "Ángulo"
L["Animate"] = "Animar"
L["Animated Expand and Collapse"] = "Animar Pliegue y Despliegue"
L["Animation relative duration description"] = [=[Duración de la animación relativa a la duración del aura, expresado en fracciones (1/2), porcentaje (50%),  o decimales (0.5).
|cFFFF0000Nota:|r si el aura no tiene progreso (por ejemplo, si no tiene un activador basado en tiempo, si el aura no tiene duración, etc.), la animación no correrá.

|cFF4444FFPor Ejemplo:|r
Si la duración de la animación es |cFF00CC0010%|r, y el disparador del aura es un beneficio que dura 20 segundos, la animación de entrada se mostrará por 2 segundos.
Si la duración de la animación es |cFF00CC0010%|r, y el disparador del aura es un beneficio sin tiempo asignado, la animación de entrada se ignorará."
]=]
L["Animations"] = "Animaciones"
L["Animation Sequence"] = "Secuencia de Animación"
-- L["Apply Template"] = ""
-- L["Arcane Orb"] = ""
-- L["At a position a bit left of Left HUD position."] = ""
-- L["At a position a bit left of Right HUD position"] = ""
-- L["At the same position as Blizzard's spell alert"] = ""
-- L["Aura Name"] = ""
L["Aura(s)"] = "Aura(s)"
-- L["Aura Type"] = ""
L["Auto"] = "Auto"
L["Automatic Icon"] = "Icono Automático"
L["Backdrop Color"] = "Color de fondo"
L["Backdrop Style"] = "Estilo de fondo"
L["Background"] = "Fondo"
L["Background Color"] = "Color de Fondo"
L["Background Inset"] = "Intercalado de Fondo"
L["Background Offset"] = "Desplazamiento del Fondo"
L["Background Texture"] = "Textura del Fondo"
L["Bar Alpha"] = "Transparencia de la Barra"
L["Bar Color"] = "Color de la Barra"
L["Bar Color Settings"] = "Configuración de color de barra"
L["Bar in Front"] = "Barra en primer plano"
L["Bar Texture"] = "Textura de la Barra"
-- L["Big Icon"] = ""
L["Blend Mode"] = "Modo de Mezcla"
-- L["Blue Rune"] = ""
-- L["Blue Sparkle Orb"] = ""
L["Border"] = "Borde"
L["Border Color"] = "Color de borde"
L["Border Inset"] = "Borde del recuadro"
L["Border Offset"] = "Desplazamiento de Borde"
L["Border Settings"] = "Configuración de bordes"
L["Border Size"] = "Tamaño del borde"
L["Border Style"] = "Estilo de borde"
L["Bottom Text"] = "Texto de Fondo"
L["Button Glow"] = "Resplandor del Botón"
L["Can be a name or a UID (e.g., party1). Only works on friendly players in your group."] = "Puede ser un nombre o un identificador de unidad(p.ej., party1). Solo funciona con personajes amistosos en tu grupo."
L["Cancel"] = "Cancelar"
L["Channel Number"] = "Número de Canal"
-- L["Chat Message"] = ""
L["Check On..."] = "Chequear..."
-- L["Children:"] = ""
L["Choose"] = "Escoger"
L["Choose Trigger"] = "Escoger Disparador"
L["Choose whether the displayed icon is automatic or defined manually"] = "Escoge si quieres que el icono mostrado sea definido automáticamente o manualmente"
L["Clone option enabled dialog"] = "Activar diálogo de clonación"
L["Close"] = "Cerrar"
L["Collapse all loaded displays"] = "Plegar todas las auras"
L["Collapse all non-loaded displays"] = "Plegar todas las auras no cargadas"
L["Color"] = "Color"
L["Compress"] = "Comprimir"
L["Constant Factor"] = "Factor Constante"
L["Controls the positioning and configuration of multiple displays at the same time"] = "Controla la posición y configuración de varias auras a la vez"
L["Cooldown"] = "Tiempo de Recarga"
L["Count"] = "Contar"
L["Creating buttons: "] = "Crear pulsadores: "
L["Creating options: "] = "Crear opciones: "
-- L["Crop"] = ""
L["Crop X"] = "Cortar X"
L["Crop Y"] = "Cortar Y"
-- L["Custom"] = ""
L["Custom Code"] = "Código Personalizado"
-- L["Custom Function"] = ""
L["Custom Trigger"] = "Disparador Personalizado"
L["Custom trigger event tooltip"] = [=[
Escoje qué eventos quieres que chequeen el disparador personalizado.
Múltiples eventos pueden ser especificados, sepáralos con comas o espacios.

|cFF4444FFPor Ejemplo:|r
UNIT_POWER, UNIT_AURA PLAYER_TARGET_CHANGED
]=]
L["Custom trigger status tooltip"] = [=[
Escoje qué eventos quieres que chequeen el disparador personalizado.
Ya que éste es un Disparador del tipo Estado, los eventos especificados pueden ser invocados por WeakAuras sin ningún argumento.
Múltiples eventos pueden ser especificados, sepáralos con comas o espacios.

|cFF4444FFPor Ejemplo:|r
UNIT_POWER, UNIT_AURA PLAYER_TARGET_CHANGED
]=]
L["Custom Untrigger"] = "Disparador No-Personalizado"
L["Debuff Type"] = "Tipo de Perjuicio"
-- L["Default"] = ""
L["Delete all"] = "Eliminar todo"
L["Delete Trigger"] = "Borrar Disparador"
L["Desaturate"] = "Desaturar"
L["Disabled"] = "Desactivado"
L["Discrete Rotation"] = "Rotación Discreta"
L["Display"] = "Mostrar"
L["Display Icon"] = "Mostrar Icono"
-- L["Displays a text, works best in combination with other displays"] = ""
L["Display Text"] = "Mostrar Texto"
L["Distribute Horizontally"] = "Distribución Horizontal"
L["Distribute Vertically"] = "Distribución Vertical"
-- L["Done"] = ""
-- L["-- Do not remove this comment, it is part of this trigger: "] = ""
L["Duration Info"] = "Información de Duración"
L["Duration (s)"] = "Duración (s)"
L["Dynamic Group"] = "Grupo Dinámico"
-- L["Dynamic information"] = ""
-- L["Dynamic information from first Active Trigger"] = ""
-- L["Dynamic information from Trigger %i"] = ""
L["Dynamic text tooltip"] = "Descripción emergente dinámica"
L["Enabled"] = "Activado"
-- L["End Angle"] = ""
L["Enter an aura name, partial aura name, or spell id"] = "Introduce el nombre del aura (total o parcial), o el identificador del aura"
-- L["Event"] = ""
-- L["Event(s)"] = ""
L["Event Type"] = "Tipo de Evento"
L["Expand all loaded displays"] = "Desplegar todas las auras"
L["Expand all non-loaded displays"] = "Desplegar todas las auras no cargadas"
L["Expand Text Editor"] = "Expandir el Editor de Texto"
L["Fade"] = "Apagar"
-- L["Fade In"] = ""
-- L["Fade Out"] = ""
L["Finish"] = "Finalizar"
-- L["Fire Orb"] = ""
L["Font"] = "Fuente"
L["Font Flags"] = "Fuente de banderas"
L["Font Size"] = "Tamaño de fuente"
L["Font Type"] = "Tipo de fuente"
L["Foreground Color"] = "Color Fontal"
L["Foreground Texture"] = "Textura Frontal"
L["Frame"] = "Macro"
L["Frame Strata"] = "Importancia del Marco"
-- L["From Template"] = ""
L["Glow Action"] = "Acción de Destello"
-- L["Green Rune"] = ""
-- L["Group"] = ""
L["Group aura count description"] = [=[La cantidad de miembros del grupo o banda que deben estar afectados por las auras indicadas para la activación.
Si el número introducido es un entero (ej. 5), la cantidad de miembros del grupo o banda que deben estar afectados será absoluta.
Si el número introducido es una fracción (1/2), decimal (0.5) o porcentaje (50%%), se interpretará como que la cantidad de miembros del grupo o banda que deben estar afectados es una fracción del total.

|cFF4444FFPor ejemplo:|r
Con |cFF00CC00> 0|r se activará cuando cualquier miembro del grupo o banda esté afectado.
Con |cFF00CC00= 100%%|r se activará cuando todos los miembros del grupo o banda estén afectados.
Con |cFF00CC00!= 2|r se activará cuando el número de miembros del grupo o banda afectados no sea 2.
Con |cFF00CC00<= 0.8|r se activará cuando menos del 80%% del grupo o banda esté afectado (4 de 5 miembros en grupos, 8 de 10 ó 20 de 25 en bandas).
Con |cFF00CC00> 1/2|r se activará cuando más de la mitad de miembros del grupo o banda estén afectados.
Con |cFF00CC00>= 0|r se activará siempre.]=]
L["Group Member Count"] = "Contador del Miembro de Grupo"
-- L["Grow"] = ""
-- L["Hawk"] = ""
L["Height"] = "Alto"
-- L["Hide"] = ""
-- L["Hide on"] = ""
L["Hide When Not In Group"] = "Esconder si no Estas Agrupado"
L["Horizontal Align"] = "Alineado Horizontal"
-- L["Horizontal Bar"] = ""
-- L["Horizontal Blizzard Raid Bar"] = ""
-- L["Huge Icon"] = ""
-- L["Hybrid Position"] = ""
-- L["Hybrid Sort Mode"] = ""
-- L["Icon"] = ""
-- L["Icon Color"] = ""
L["Icon Info"] = "Información del Icono"
L["Icon Inset"] = "Interior del Icono" -- Needs review
L["Ignored"] = "Ignorar"
L["%i Matches"] = "%i Correspondencias"
L["Import"] = "Importar"
L["Import a display from an encoded string"] = "Importar un aura desde un texto cifrado"
-- L["Inverse"] = ""
L["Justify"] = "Justificar"
-- L["Leaf"] = ""
-- L["Left 2 HUD position"] = ""
-- L["Left HUD position"] = ""
L["Left Text"] = "Texto Izquierdo"
L["Load"] = "Cargar"
L["Loaded"] = "Cargado"
-- L["Low Mana"] = ""
L["Main"] = "Principal"
L["Manage displays defined by Addons"] = "Administra Auras definidas por Addons"
-- L["Medium Icon"] = ""
-- L["Message"] = ""
L["Message Prefix"] = "Prefijo del Mensaje"
L["Message Suffix"] = "Sufijo del Mensaje"
-- L["Message Type"] = ""
L["Mirror"] = "Reflejar"
L["Model"] = "Modelo"
L["Multiple Displays"] = "Múltiples auras"
L["Multiple Triggers"] = "Disparadores Múltiples"
L["Multiselect ignored tooltip"] = [=[
|cFFFF0000Ignorado|r - |cFF777777Único|r - |cFF777777Múltiple|r
Ésta opción no será usada al determinar cuándo se mostrará el aura]=]
L["Multiselect multiple tooltip"] = [=[
|cFF777777Ignorado|r - |cFF777777Único|r - |cFF00FF00Múltiple|r
Cualquier combinación de valores es posible.]=]
L["Multiselect single tooltip"] = [=[
|cFF777777Ignorado|r - |cFF00FF00Único|r - |cFF777777Múltiple|r
Sólo un valor coincidente puede ser escogido.]=]
L["Name Info"] = "Información del Nombre"
L["Negator"] = "Negar"
-- L["Never"] = ""
L["New"] = "Nuevo"
L["No"] = "no"
-- L["None"] = ""
L["Not all children have the same value for this option"] = "No todos los hijos contienen la misma configuración."
L["Not Loaded"] = "No Cargado"
L["No tooltip text"] = "Sin Texto de Descripción"
-- L["Offer a guided way to create auras for your class"] = ""
L["% of Progress"] = "% de Progreso"
L["Okay"] = "Aceptar"
L["On Hide"] = "Ocultar"
-- L["On Init"] = ""
L["Only match auras cast by people other than the player"] = "Solamente corresponder auras conjuradas por otros jugadores"
L["Only match auras cast by the player"] = "Solamente corresponder auras conjuradas por ti"
L["On Show"] = "Mostrar"
L["Operator"] = "Operador"
L["or"] = "o"
-- L["Orange Rune"] = ""
L["Orientation"] = "Orientación"
L["Outline"] = "Contorno"
L["Own Only"] = "Solo Mías"
-- L["Paste text below"] = ""
L["Play Sound"] = "Reproducir Sonido"
-- L["Portrait Zoom"] = ""
-- L["Preset"] = ""
L["Prevents duration information from decreasing when an aura refreshes. May cause problems if used with multiple auras with different durations."] = "Prevenir que el temporizador siga contando cuando el aura se refresca. Ten cuidado, pueden aparecer problemas si usas múltiples auras con múltiples duraciones."
-- L["Processed %i chars"] = ""
L["Progress Bar"] = "Barra de Progreso"
L["Progress Texture"] = "Texture de Progreso"
-- L["Purple Rune"] = ""
-- L["Radius"] = ""
L["Re-center X"] = "Re-centrar X"
L["Re-center Y"] = "Re-centrar Y"
-- L["Remaining Time"] = ""
L["Remaining Time Precision"] = "Precisión del Tiempo Restante"
L["Required For Activation"] = "Necesario para Activación"
-- L["Right 2 HUD position"] = ""
L["Right-click for more options"] = "Clic derecho para más opciones"
-- L["Right HUD position"] = ""
L["Right Text"] = "Texto Derecho"
L["Rotate"] = "Rotación"
L["Rotate In"] = "Rotar"
L["Rotate Out"] = "Rotar"
L["Rotate Text"] = "Rotar Texto"
L["Rotation"] = "Rotación"
-- L["Rotation Mode"] = ""
L["Same"] = "Igual"
-- L["Scale"] = ""
L["Search"] = "Buscar"
L["Select the auras you always want to be listed first"] = "Selecciona las auras que quieres que siempre sean listadas primero" -- Needs review
L["Send To"] = "Envar A"
L["Show all matches (Auto-clone)"] = "Mostrar todas las coincidencias (Auto-clonar)"
-- L["Show model of unit "] = ""
L["Show players that are |cFFFF0000not affected"] = "Mostrar jugadores |cFFFF0000no afectados"
L["Shows a 3D model from the game files"] = "Muestra un modelo 3D directamente de los ficheros de WoW"
L["Shows a custom texture"] = "Muestra una textura"
L["Shows a progress bar with name, timer, and icon"] = "Muestra una barra de progreso con nombres, temporizadores, y icono"
L["Shows a spell icon with an optional cooldown overlay"] = "Muestra un icono como aura con máscaras opcionales" -- Needs review
L["Shows a texture that changes based on duration"] = "Muestra una textura que cambia con el tiempo"
L["Shows one or more lines of text, which can include dynamic information such as progress or stacks"] = "Muestra una o varias lineas de texto, capaz de contener información cambiante como acumulaciones y/o progresos"
L["Size"] = "Tamaño"
L["Slide"] = "Arrastrar"
L["Slide In"] = "Arrastrar Dentro"
L["Slide Out"] = "Arrastrar"
-- L["Small Icon"] = ""
L["Sort"] = "Ordenar"
L["Sound"] = "Sonido"
L["Sound Channel"] = "Canal de Sonido"
L["Sound File Path"] = "Ruta al Fichero de Sonido"
-- L["Sound Kit ID"] = ""
L["Space"] = "Espacio"
L["Space Horizontally"] = "Espacio Horizontal"
L["Space Vertically"] = "Espacio Vertical"
-- L["Spark"] = ""
-- L["Spark Settings"] = ""
-- L["Spark Texture"] = ""
-- L["Specific Unit"] = ""
L["Spell ID"] = "ID de Hechizo"
L["Spell ID dialog"] = "Diálogo de ID de Hechizo"
L["Stack Count"] = "Contar Acumulaciones"
L["Stack Info"] = "Información de Acumulaciones"
-- L["Stacks"] = ""
L["Stacks Settings"] = "Configuración de montones"
L["Stagger"] = "Tambaleo"
-- L["Star"] = ""
L["Start"] = "Empezar"
-- L["Start Angle"] = ""
-- L["Status"] = ""
L["Stealable"] = "Puede Robarse"
L["Sticky Duration"] = "Duración Adhesiva"
-- L["Symbol Settings"] = ""
L["Temporary Group"] = "Grupo Temporal"
L["Text"] = "Texto"
L["Text Color"] = "Color del Texto"
L["Text Position"] = "Posición del Texto"
L["Texture"] = "Textura"
L["Texture Info"] = "Información de Textura" -- Needs review
L["The children of this group have different display types, so their display options cannot be set as a group."] = "No todos los hijos contienen la misma configuración, así que no los puedes configurar bajo el mismo perfil."
L["The duration of the animation in seconds."] = "Duración de la animación (en segundos)."
L["The type of trigger"] = "Tipo de Activador"
-- L["This region of type \"%s\" is not supported."] = ""
L["Time in"] = "Contar En"
-- L["Tiny Icon"] = ""
L["Toggle the visibility of all loaded displays"] = "Alterar la visibilidad de todas las auras cargadas"
L["Toggle the visibility of all non-loaded displays"] = "Alterar la visibilidad de todas las auras no cargadas"
L["to group's"] = "al groupo"
L["Tooltip"] = "Descriptión emergente"
L["Tooltip on Mouseover"] = "Descripción Emergente al pasar el ratón"
-- L["Top HUD position"] = ""
L["Top Text"] = "Texto de Arriba"
L["to screen's"] = "a pantalla"
L["Total Time Precision"] = "Precisión del cronómetro"
L["Trigger"] = "Disparador"
L["Trigger %d"] = "Disparador %d"
L["Type"] = "Tipo"
-- L["Unit"] = ""
L["Unlike the start or finish animations, the main animation will loop over and over until the display is hidden."] = "Ignorar animaciones de inicio y final: la animación principal se repetirá hasta que el aura se oculte."
L["Update Custom Text On..."] = "Actualizar Texto Personalizado En..."
L["Use Full Scan (High CPU)"] = "Escaneo Total (carga el procesador)"
-- L["Use SetTransform api"] = ""
L["Use tooltip \"size\" instead of stacks"] = "Usa \"tamaño\" en vez de acumulaciones"
L["Vertical Align"] = "Alineado Vertical"
-- L["Vertical Bar"] = ""
-- L["WeakAurasOptions"] = ""
L["Width"] = "Ancho"
L["X Offset"] = "X Posicion"
-- L["X Rotation"] = ""
L["X Scale"] = "X Escala"
-- L["Yellow Rune"] = ""
L["Yes"] = "Sí"
L["Y Offset"] = "Y Posicion"
-- L["Y Rotation"] = ""
L["Y Scale"] = "Y Escala"
L["Z Offset"] = "Desplazamiento en Z"
L["Zoom"] = "Ampliación"
L["Zoom In"] = "Acercar"
L["Zoom Out"] = "Alejar"
-- L["Z Rotation"] = ""



