local L = LibStub("AceLocale-3.0"):NewLocale("GSE", "enUS", true)

-- Options translation
L["  The Alternative ClassID is "] = "  The Alternative ClassID is "
L[" already exists."] = " already exists."
L[" Deleted Orphaned Macro "] = " Deleted Orphaned Macro "
L[" equals "] = " equals "
L[" equals currentclassid "] = " equals currentclassid "
L[" from "] = " from "
L[" From library"] = " From library"
L[" has been added as a new version and set to active.  Please review if this is as expected."] = " has been added as a new version and set to active.  Please review if this is as expected."
L[" is not available.  Unable to translate sequence "] = " is not available.  Unable to translate sequence "
L[" is unknown."] = " is unknown."
L[" macros per Account.  You currently have "] = " macros per Account.  You currently have "
L[" macros per character.  You currently have "] = " macros per character.  You currently have "
L[" not added to list."] = " not added to list."
L[" saved as version "] = " saved as version "
L[" sent"] = " sent"
L[" Sequence named "] = " Sequence named "
L[" tried to overwrite the version already loaded from "] = " tried to overwrite the version already loaded from "
L[" was imported with the following errors."] = " was imported with the following errors."
L[" with iconid "] = " with iconid "
L[". Overriding with information for current spec "] = ". Overriding with information for current spec "
L[". This version was not loaded."] = ". This version was not loaded."
L["/gs |r to get started."] = "/gs |r to get started."
L["/gs cleanorphans|r will loop through your macros and delete any left over GS-E macros that no longer have a sequence to match them."] = "/gs cleanorphans|r will loop through your macros and delete any left over GS-E macros that no longer have a sequence to match them."
L["/gs help|r to get started."] = "/gs help|r to get started."
L["/gs listall|r will produce a list of all available macros with some help information."] = "/gs listall|r will produce a list of all available macros with some help information."
L["/gs showspec|r will show your current Specialisation and the SPECID needed to tag any existing macros."] = "/gs showspec|r will show your current Specialisation and the SPECID needed to tag any existing macros."
L["/gs|r again."] = "/gs|r again."
L["/gs|r will list any macros available to your spec.  This will also add any macros available for your current spec to the macro interface."] = "/gs|r will list any macros available to your spec.  This will also add any macros available for your current spec to the macro interface."
L["/gsse |r to get started."] = "/gsse |r to get started."
L[":|r The Sequence Translator allows you to use GS-E on other languages than enUS.  It will translate sequences to match your language.  If you also have the Sequence Editor you can translate sequences between languages.  The GS-E Sequence Translator is available on curse.com"] = ":|r The Sequence Translator allows you to use GS-E on other languages than enUS.  It will translate sequences to match your language.  If you also have the Sequence Editor you can translate sequences between languages.  The GS-E Sequence Translator is available on curse.com"
L[":|r To get started "] = ":|r To get started "
L[":|r You cannot delete the only copy of a sequence."] = ":|r You cannot delete the only copy of a sequence."
L[":|r Your current Specialisation is "] = ":|r Your current Specialisation is "
L["[GNOME] syntax error on line %d of Sequences.lua:|r %s"] = "[GNOME] syntax error on line %d of Sequences.lua:|r %s"
L["], (GSisEmpty(GSMasterOptions.SequenceLibrary["] = "], (GSisEmpty(GSMasterOptions.SequenceLibrary["
L["].lang or GetLocale()), key)"] = "].lang or GetLocale()), key)"
L["].lang) and GSMasterOptions.SequenceLibrary["] = "].lang) and GSMasterOptions.SequenceLibrary["
L["|cffff0000GS-E:|r Gnome Sequencer - Enhanced Options"] = "|cffff0000GS-E:|r Gnome Sequencer - Enhanced Options"
L["|r Incomplete Sequence Definition - This sequence has no further information "] = "|r Incomplete Sequence Definition - This sequence has no further information "
L["|r.  As a result this macro was not created.  Please delete some macros and reenter "] = "|r.  As a result this macro was not created.  Please delete some macros and reenter "
L["|r.  You can also have a  maximum of "] = "|r.  You can also have a  maximum of "
L["<DEBUG> |r "] = "<DEBUG> |r "
L["<SEQUENCEDEBUG> |r "] = "<SEQUENCEDEBUG> |r "
L["A sequence colision has occured. "] = "A sequence collision has occured. "
L["A sequence collision has occured. "] = "A sequence collision has occured. "
L["A sequence collision has occured.  Extra versions of this macro have been loaded.  Manage the sequence to determine how to use them "] = "A sequence collision has occured.  Extra versions of this macro have been loaded.  Manage the sequence to determine how to use them "
L["A sequence collision has occured.  Your local version of "] = "A sequence collision has occured.  Your local version of "
L["Actions"] = "Actions"
L["Active Version "] = "Active Version "
L["Active Version: "] = "Active Version: "
L[ [=[Addin Version %s contained versions for the following macros: 
%s]=] ] = [=[Addin Version %s contained versions for the following macros: 
%s]=]
L["Adding missing Language :"] = "Adding missing Language :"
L["Are you sure you want to delete %s?  This will delete the macro and all versions.  This action cannot be undone."] = "Are you sure you want to delete %s?  This will delete the macro and all versions.  This action cannot be undone."
L["As GS-E is updated, there may be left over macros that no longer relate to sequences.  This will check for these automatically on logout.  Alternatively this check can be run via /gs cleanorphans"] = "As GS-E is updated, there may be left over macros that no longer relate to sequences.  This will check for these automatically on logout.  Alternatively this check can be run via /gs cleanorphans"
L["Author"] = "Author"
L["Author Colour"] = "Author Colour"
L["Auto Create Class Macro Stubs"] = "Auto Create Class Macro Stubs"
L["Auto Create Global Macro Stubs"] = "Auto Create Global Macro Stubs"
L["Available Addons"] = "Available Addons"
L["Belt"] = "Belt"
L["Blizzard Functions Colour"] = "Blizzard Functions Colour"
L["By setting the default Icon for all macros to be the QuestionMark, the macro button on your toolbar will change every key hit."] = "By setting the default Icon for all macros to be the QuestionMark, the macro button on your toolbar will change every key hit."
L["By setting this value the Sequence Editor will show every macro for every class."] = "By setting this value the Sequence Editor will show every macro for every class."
L["By setting this value the Sequence Editor will show every macro for your class."] = "By setting this value the Sequence Editor will show every macro for your class."
L["Cancel"] = "Cancel"
L["Checking if specID "] = "Checking if specID "
L["Choose Language"] = "Choose Language"
L["Class = "] = "Class = "
L["Classwide Macro"] = "Classwide Macro"
L["Clear"] = "Clear"
L["Clear Errors"] = "Clear Errors"
L["Close"] = "Close"
L["Close to Maximum Macros.|r  You can have a maximum of "] = "Close to Maximum Macros.|r  You can have a maximum of "
L["Close to Maximum Personal Macros.|r  You can have a maximum of "] = "Close to Maximum Personal Macros.|r  You can have a maximum of "
L["Colour"] = "Colour"
L["Colour and Accessibility Options"] = "Colour and Accessibility Options"
L["Combat"] = "Combat"
L["Command Colour"] = "Command Colour"
L["Completely New GS Macro."] = "Completely New GS Macro."
L["Conditionals Colour"] = "Conditionals Colour"
L["Configuration"] = "Configuration"
L["Contributed by: "] = "Contributed by: "
L["Copy this link and open it in a Browser."] = "Copy this link and open it in a Browser."
L["Create Icon"] = "Create Icon"
L["Create Macro"] = "Create Macro"
L["createButton PostMacro: "] = "createButton PostMacro: "
L["createButton PreMacro: "] = "createButton PreMacro: "
L["Creating New Sequence."] = "Creating New Sequence."
L["Cycle Version "] = "Cycle Version "
L["Debug"] = "Debug"
L["Debug Mode Options"] = "Debug Mode Options"
L["Debug Output Options"] = "Debug Output Options"
L["Debug Sequence Execution"] = "Debug Sequence Execution"
L["Default Version"] = "Default Version"
L["Delete"] = "Delete"
L["Delete Icon"] = "Delete Icon"
L["Delete Orphaned Macros on Logout"] = "Delete Orphaned Macros on Logout"
L["Delete Version"] = "Delete Version"
L["Different helpTxt"] = "Different helpTxt"
L["Different PostMacro"] = "Different PostMacro"
L["Different PreMacro"] = "Different PreMacro"
L["Different Sequence Steps"] = "Different Sequence Steps"
L["Different specID"] = "Different specID"
L["Different StepFunction"] = "Different StepFunction"
L["Disable"] = "Disable"
L["Disable Sequence"] = "Disable Sequence"
L["Display debug messages in Chat Window"] = "Display debug messages in Chat Window"
L["Dump of GS Debug messages"] = "Dump of GS Debug messages"
L["Edit"] = "Edit"
L["Editor Colours"] = "Editor Colours"
L["Emphasis Colour"] = "Emphasis Colour"
L["Enable"] = "Enable"
L["Enable Debug for the following Modules"] = "Enable Debug for the following Modules"
L["Enable Mod Debug Mode"] = "Enable Mod Debug Mode"
L["Enable Sequence"] = "Enable Sequence"
L["Entering GSSplitMeIntolines with :"] = "Entering GSSplitMeIntolines with :"
L["Export"] = "Export"
L["Export a Sequence"] = "Export a Sequence"
L["Filter Macro Selection"] = "Filter Macro Selection"
L["FYou cannot delete this version of a sequence.  This version will be reloaded as it is contained in "] = "FYou cannot delete this version of a sequence.  This version will be reloaded as it is contained in "
L["Gameplay Options"] = "Gameplay Options"
L["GCD Delay:"] = "GCD Delay:"
L["General"] = "General"
L["General Options"] = "General Options"
L["Gnome Sequencer: Export a Sequence String."] = "Gnome Sequencer: Export a Sequence String."
L["Gnome Sequencer: Import a Macro String."] = "Gnome Sequencer: Import a Macro String."
L["Gnome Sequencer: Record your rotation to a macro."] = "Gnome Sequencer: Record your rotation to a macro."
L["Gnome Sequencer: Sequence Debugger. Monitor the Execution of your Macro"] = "Gnome Sequencer: Sequence Debugger. Monitor the Execution of your Macro"
L["Gnome Sequencer: Sequence Editor."] = "Gnome Sequencer: Sequence Editor."
L["Gnome Sequencer: Sequence Version Manager"] = "Gnome Sequencer: Sequence Version Manager"
L["Gnome Sequencer: Sequence Viewer"] = "Gnome Sequencer: Sequence Viewer"
L["GnomeSequencer was originally written by semlar of wowinterface.com."] = "GnomeSequencer was originally written by semlar of wowinterface.com."
L["GnomeSequencer-Enhanced"] = "GnomeSequencer-Enhanced"
L["GnomeSequencer-Enhanced loaded.|r  Type "] = "GnomeSequencer-Enhanced loaded.|r  Type "
L["GSE"] = "GSE"
L["GSE allows plugins to load Macro Collections as plugins.  You can reload a collection by pressing the button below."] = "GSE allows plugins to load Macro Collections as plugins.  You can reload a collection by pressing the button below."
L["GS-E can save all macros or only those versions that you have created locally.  Turning this off will cache all macros in your WTF\\GS-Core.lua variables file but will increase load times and potentially cause colissions."] = "GS-E can save all macros or only those versions that you have created locally.  Turning this off will cache all macros in your WTF\\GS-Core.lua variables file but will increase load times and potentially cause colissions."
L["GS-E is out of date. You can download the newest version from https://mods.curse.com/addons/wow/gnomesequencer-enhanced."] = "GS-E is out of date. You can download the newest version from https://mods.curse.com/addons/wow/gnomesequencer-enhanced."
L["GSE is out of date. You can download the newest version from https://mods.curse.com/addons/wow/gnomesequencer-enhanced."] = "GSE is out of date. You can download the newest version from https://mods.curse.com/addons/wow/gnomesequencer-enhanced."
L["GSE Macro"] = "GSE Macro"
L["GS-E Plugins"] = "GS-E Plugins"
L["GS-E: Left Click to open the Sequence Editor"] = "GS-E: Left Click to open the Sequence Editor"
L["GS-E: Middle Click to open the Transmission Interface"] = "GS-E: Middle Click to open the Transmission Interface"
L["GS-E: Right Click to open the Sequence Debugger"] = "GS-E: Right Click to open the Sequence Debugger"
L["GSSE:loadSequence "] = "GSSE:loadSequence "
L["GSTranslateSequenceFromTo(GSMasterOptions.SequenceLibrary["] = "GSTranslateSequenceFromTo(GSMasterOptions.SequenceLibrary["
L["GSUpdateSequence PostMacro updated to: "] = "GSUpdateSequence PostMacro updated to: "
L["GSUpdateSequence PreMacro updated to: "] = "GSUpdateSequence PreMacro updated to: "
L["has been disabled.  The Macro stub for this sequence will be deleted and will not be recreated until you re-enable this sequence.  It will also not appear in the /gs list until it is recreated."] = "has been disabled.  The Macro stub for this sequence will be deleted and will not be recreated until you re-enable this sequence.  It will also not appear in the /gs list until it is recreated."
L["has been enabled.  The Macro stub is now available in your Macro interface."] = "has been enabled.  The Macro stub is now available in your Macro interface."
L["Head"] = "Head"
L["Help Colour"] = "Help Colour"
L["Help Information"] = "Help Information"
L["Help Link"] = "Help Link"
L["Help URL"] = "Help URL"
L["I am loaded"] = "I am loaded"
L["Icon Colour"] = "Icon Colour"
L["Icon: "] = "Icon: "
L["If you load Gnome Sequencer - Enhanced and the Sequence Editor and want to create new macros from scratch, this will enable a first cut sequenced template that you can load into the editor as a starting point.  This enables a Hello World macro called Draik01.  You will need to do a /console reloadui after this for this to take effect."] = "If you load Gnome Sequencer - Enhanced and the Sequence Editor and want to create new macros from scratch, this will enable a first cut sequenced template that you can load into the editor as a starting point.  This enables a Hello World macro called Draik01.  You will need to do a /console reloadui after this for this to take effect."
L["Import"] = "Import"
L["Import Macro from Forums"] = "Import Macro from Forums"
L["Imported new sequence "] = "Imported new sequence "
L["Incorporate the belt slot into the KeyRelease. This is the equivalent of /use [combat] 5 in a KeyRelease."] = "Incorporate the belt slot into the KeyRelease. This is the equivalent of /use [combat] 5 in a KeyRelease."
L["Incorporate the belt slot into the PostMacro. This is the equivalent of /use [combat] 5 in a PostMacro."] = "Incorporate the belt slot into the PostMacro. This is the equivalent of /use [combat] 5 in a PostMacro."
L["Incorporate the first ring slot into the KeyRelease. This is the equivalent of /use [combat] 11 in a KeyRelease."] = "Incorporate the first ring slot into the KeyRelease. This is the equivalent of /use [combat] 11 in a KeyRelease."
L["Incorporate the first ring slot into the PostMacro. This is the equivalent of /use [combat] 11 in a PostMacro."] = "Incorporate the first ring slot into the PostMacro. This is the equivalent of /use [combat] 11 in a PostMacro."
L["Incorporate the first trinket slot into the KeyRelease. This is the equivalent of /use [combat] 13 in a KeyRelease."] = "Incorporate the first trinket slot into the KeyRelease. This is the equivalent of /use [combat] 13 in a KeyRelease."
L["Incorporate the first trinket slot into the PostMacro. This is the equivalent of /use [combat] 13 in a PostMacro."] = "Incorporate the first trinket slot into the PostMacro. This is the equivalent of /use [combat] 13 in a PostMacro."
L["Incorporate the Head slot into the KeyRelease. This is the equivalent of /use [combat] 1 in a KeyRelease."] = "Incorporate the Head slot into the KeyRelease. This is the equivalent of /use [combat] 1 in a KeyRelease."
L["Incorporate the Head slot into the PostMacro. This is the equivalent of /use [combat] 1 in a PostMacro."] = "Incorporate the Head slot into the PostMacro. This is the equivalent of /use [combat] 1 in a PostMacro."
L["Incorporate the neck slot into the KeyRelease. This is the equivalent of /use [combat] 2 in a KeyRelease."] = "Incorporate the neck slot into the KeyRelease. This is the equivalent of /use [combat] 2 in a KeyRelease."
L["Incorporate the neck slot into the PostMacro. This is the equivalent of /use [combat] 2 in a PostMacro."] = "Incorporate the neck slot into the PostMacro. This is the equivalent of /use [combat] 2 in a PostMacro."
L["Incorporate the second ring slot into the KeyRelease. This is the equivalent of /use [combat] 12 in a KeyRelease."] = "Incorporate the second ring slot into the KeyRelease. This is the equivalent of /use [combat] 12 in a KeyRelease."
L["Incorporate the second ring slot into the PostMacro. This is the equivalent of /use [combat] 12 in a PostMacro."] = "Incorporate the second ring slot into the PostMacro. This is the equivalent of /use [combat] 12 in a PostMacro."
L["Incorporate the second trinket slot into the KeyRelease. This is the equivalent of /use [combat] 14 in a KeyRelease."] = "Incorporate the second trinket slot into the KeyRelease. This is the equivalent of /use [combat] 14 in a KeyRelease."
L["Incorporate the second trinket slot into the PostMacro. This is the equivalent of /use [combat] 14 in a PostMacro."] = "Incorporate the second trinket slot into the PostMacro. This is the equivalent of /use [combat] 14 in a PostMacro."
L["Inner Loop End"] = "Inner Loop End"
L["Inner Loop Limit"] = "Inner Loop Limit"
L["Inner Loop Start"] = "Inner Loop Start"
L["is currently disabled from use."] = "is currently disabled from use."
L["KeyPress"] = "KeyPress"
L["KeyRelease"] = "KeyRelease"
L["Language"] = "Language"
L["Language Colour"] = "Language Colour"
L["Legacy GS/GSE1 Macro"] = "Legacy GS/GSE1 Macro"
L["Like a /castsequence macro, it cycles through a series of commands when the button is pushed. However, unlike castsequence, it uses macro text for the commands instead of spells, and it advances every time the button is pushed instead of stopping when it can't cast something."] = "Like a /castsequence macro, it cycles through a series of commands when the button is pushed. However, unlike castsequence, it uses macro text for the commands instead of spells, and it advances every time the button is pushed instead of stopping when it can't cast something."
L["Line : "] = "Line : "
L["Load"] = "Load"
L["Load Sequence"] = "Load Sequence"
L["Macro Collection to Import."] = "Macro Collection to Import."
L["Macro Found "] = "Macro Found "
L["Macro Icon"] = "Macro Icon"
L["Macro Import Successful."] = "Macro Import Successful."
L["Macro unable to be imported."] = "Macro unable to be imported."
L["Macro Version %d deleted."] = "Macro Version %d deleted."
L["Make Active"] = "Make Active"
L["Manage Versions"] = "Manage Versions"
L["Matching helpTxt"] = "Matching helpTxt"
L["Matching PostMacro"] = "Matching PostMacro"
L["Matching PreMacro"] = "Matching PreMacro"
L["Matching specID"] = "Matching specID"
L["Matching StepFunction"] = "Matching StepFunction"
L["Moving on - "] = "Moving on - "
L["Moving on - LiveTest.PosMacro already exists."] = "Moving on - LiveTest.PosMacro already exists."
L["Moving on - LiveTest.PreMacro already exists."] = "Moving on - LiveTest.PreMacro already exists."
L["Moving on - macro for "] = "Moving on - macro for "
L["Mythic"] = "Mythic"
L["Neck"] = "Neck"
L["New"] = "New"
L["No"] = "No"
L["No Active Version"] = "No Active Version"
L["No Help Information "] = "No Help Information "
L["No Help Information Available"] = "No Help Information Available"
L["No Macro Found. Possibly different spec for Sequence "] = "No Macro Found. Possibly different spec for Sequence "
L["No Sequence Icon setting to "] = "No Sequence Icon setting to "
L["No Sequences present so none displayed in the list."] = "No Sequences present so none displayed in the list."
L["No Specialisation information for sequence "] = "No Specialisation information for sequence "
L["No value"] = "No value"
L["none"] = "none"
L["Normal Colour"] = "Normal Colour"
L["of no value"] = "of no value"
L["Only Save Local Macros"] = "Only Save Local Macros"
L["Options"] = "Options"
L["Output"] = "Output"
L["Output the action for each button press to verify StepFunction and spell availability."] = "Output the action for each button press to verify StepFunction and spell availability."
L["Pause"] = "Pause"
L["Picks a Custom Colour for emphasis."] = "Picks a Custom Colour for emphasis."
L["Picks a Custom Colour for the Author."] = "Picks a Custom Colour for the Author."
L["Picks a Custom Colour for the Commands."] = "Picks a Custom Colour for the Commands."
L["Picks a Custom Colour for the Mod Names."] = "Picks a Custom Colour for the Mod Names."
L["Picks a Custom Colour to be used for braces and indents."] = "Picks a Custom Colour to be used for braces and indents."
L["Picks a Custom Colour to be used for Icons."] = "Picks a Custom Colour to be used for Icons."
L["Picks a Custom Colour to be used for language descriptors"] = "Picks a Custom Colour to be used for language descriptors"
L["Picks a Custom Colour to be used for macro conditionals eg [mod:shift]"] = "Picks a Custom Colour to be used for macro conditionals eg [mod:shift]"
L["Picks a Custom Colour to be used for Macro Keywords like /cast and /target"] = "Picks a Custom Colour to be used for Macro Keywords like /cast and /target"
L["Picks a Custom Colour to be used for numbers."] = "Picks a Custom Colour to be used for numbers."
L["Picks a Custom Colour to be used for Spells and Abilities."] = "Picks a Custom Colour to be used for Spells and Abilities."
L["Picks a Custom Colour to be used for StepFunctions."] = "Picks a Custom Colour to be used for StepFunctions."
L["Picks a Custom Colour to be used for strings."] = "Picks a Custom Colour to be used for strings."
L["Picks a Custom Colour to be used for unknown terms."] = "Picks a Custom Colour to be used for unknown terms."
L["Picks a Custom Colour to be used normally."] = "Picks a Custom Colour to be used normally."
L["Please wait till you have left combat before using the Sequence Editor."] = "Please wait till you have left combat before using the Sequence Editor."
L["Plugins"] = "Plugins"
L["PostMacro"] = "PostMacro"
L["PreMacro"] = "PreMacro"
L["Prevent Sound Errors"] = "Prevent Sound Errors"
L["Prevent UI Errors"] = "Prevent UI Errors"
L["Priority List (1 12 123 1234)"] = "Priority List (1 12 123 1234)"
L["PVP"] = "PVP"
L["PVP setting changed to Default."] = "PVP setting changed to Default."
L["Raid"] = "Raid"
L["Ready to Send"] = "Ready to Send"
L["Received Sequence "] = "Received Sequence "
L["Record"] = "Record"
L["Record Macro"] = "Record Macro"
L["Registered Addons"] = "Registered Addons"
L["Reloading Sequences"] = "Reloading Sequences"
L["Removing "] = "Removing "
L["Require Target to use"] = "Require Target to use"
L["Reset Macro when out of combat"] = "Reset Macro when out of combat"
L["Resets"] = "Resets"
L["Resets macros back to the initial state when out of combat."] = "Resets macros back to the initial state when out of combat."
L["Resume"] = "Resume"
L["Ring 1"] = "Ring 1"
L["Ring 2"] = "Ring 2"
L["Same Sequence Steps"] = "Same Sequence Steps"
L["Save"] = "Save"
L["Seed Initial Macro"] = "Seed Initial Macro"
L["Select Other Version"] = "Select Other Version"
L["Selecting tab: "] = "Selecting tab: "
L["Send"] = "Send"
L["Send To"] = "Send To"
L["Sequence"] = "Sequence"
L["Sequence %s saved."] = "Sequence %s saved."
L["Sequence Author set to Unknown"] = "Sequence Author set to Unknown"
L["Sequence Debugger"] = "Sequence Debugger"
L["Sequence Editor"] = "Sequence Editor"
L["Sequence Name"] = "Sequence Name"
L["Sequence Name: "] = "Sequence Name: "
L["Sequence Saved as version "] = "Sequence Saved as version "
L["Sequence specID set to current spec of "] = "Sequence specID set to current spec of "
L["Sequence Viewer"] = "Sequence Viewer"
L["sequenceIndex: "] = "sequenceIndex: "
L["SequenceSpecID: "] = "SequenceSpecID: "
L["Sequential (1 2 3 4)"] = "Sequential (1 2 3 4)"
L["Set Default Icon QuestionMark"] = "Set Default Icon QuestionMark"
L["Setting Editor clean "] = "Setting Editor clean "
L["Show All Macros in Editor"] = "Show All Macros in Editor"
L["Show Class Macros in Editor"] = "Show Class Macros in Editor"
L["Source "] = "Source "
L["Source Language "] = "Source Language "
L["Spec = "] = "Spec = "
L["Specialisation / Class ID"] = "Specialisation / Class ID"
L["Specialization Specific Macro"] = "Specialization Specific Macro"
L["SpecID/ClassID Colour"] = "SpecID/ClassID Colour"
L["Spell Colour"] = "Spell Colour"
L["Step Function"] = "Step Function"
L["Step Functions"] = "Step Functions"
L["Stop"] = "Stop"
L["Store Debug Messages"] = "Store Debug Messages"
L["Store output of debug messages in a Global Variable that can be referrenced by other mods."] = "Store output of debug messages in a Global Variable that can be referrenced by other mods."
L["String Colour"] = "String Colour"
L["String Icon "] = "String Icon "
L["Talents"] = "Talents"
L["Target"] = "Target"
L["Target language "] = "Target language "
L["Testing "] = "Testing "
L["Testing String: "] = "Testing String: "
L["The command "] = "The command "
L["The Custom StepFunction Specified is not recognised and has been ignored."] = "The Custom StepFunction Specified is not recognised and has been ignored."
L["The Macro Translator will translate an English sequence to your local language for execution.  It can also be used to translate a sequence into a different language.  It is also used for syntax based colour markup of Sequences in the editor."] = "The Macro Translator will translate an English sequence to your local language for execution.  It can also be used to translate a sequence into a different language.  It is also used for syntax based colour markup of Sequences in the editor."
L["The Sample Macros have been reloaded."] = "The Sample Macros have been reloaded."
L["The Sequence Editor can attempt to parse the Sequences, KeyPress and KeyRelease in realtime.  This is still experimental so can be turned off."] = "The Sequence Editor can attempt to parse the Sequences, KeyPress and KeyRelease in realtime.  This is still experimental so can be turned off."
L["The Sequence Editor can attempt to parse the Sequences, PreMacro and PostMacro in realtime.  This is still experimental so can be turned off."] = "The Sequence Editor can attempt to parse the Sequences, PreMacro and PostMacro in realtime.  This is still experimental so can be turned off."
L["The Sequence Editor is an addon for GnomeSequencer-Enhanced that allows you to view and edit Sequences in game.  Type "] = "The Sequence Editor is an addon for GnomeSequencer-Enhanced that allows you to view and edit Sequences in game.  Type "
L["There are No Macros Loaded for this class.  Would you like to load the Sample Macro?"] = "There are No Macros Loaded for this class.  Would you like to load the Sample Macro?"
L["This change will not come into effect until you save this macro."] = "This change will not come into effect until you save this macro."
L["This is a small addon that allows you create a sequence of macros to be executed at the push of a button."] = "This is a small addon that allows you create a sequence of macros to be executed at the push of a button."
L["This is the only version of this macro.  Delete the entire macro to delete this version."] = "This is the only version of this macro.  Delete the entire macro to delete this version."
L["This option clears errors and stack traces ingame.  This is the equivalent of /run UIErrorsFrame:Clear() in a KeyRelease.  Turning this on will trigger a Scam warning about running custom scripts."] = "This option clears errors and stack traces ingame.  This is the equivalent of /run UIErrorsFrame:Clear() in a KeyRelease.  Turning this on will trigger a Scam warning about running custom scripts."
L["This option clears errors and stack traces ingame.  This is the equivalent of /run UIErrorsFrame:Clear() in a PostMacro.  Turning this on will trigger a Scam warning about running custom scripts."] = "This option clears errors and stack traces ingame.  This is the equivalent of /run UIErrorsFrame:Clear() in a PostMacro.  Turning this on will trigger a Scam warning about running custom scripts."
L["This option dumps extra trace information to your chat window to help troubleshoot problems with the mod"] = "This option dumps extra trace information to your chat window to help troubleshoot problems with the mod"
L["This option hide error sounds like \"That is out of range\" from being played while you are hitting a GS Macro.  This is the equivalent of /console Sound_EnableErrorSpeech lines within a Sequence.  Turning this on will trigger a Scam warning about running custom scripts."] = "This option hide error sounds like \"That is out of range\" from being played while you are hitting a GS Macro.  This is the equivalent of /console Sound_EnableErrorSpeech lines within a Sequence.  Turning this on will trigger a Scam warning about running custom scripts."
L["This option hides text error popups and dialogs and stack traces ingame.  This is the equivalent of /script UIErrorsFrame:Hide() in a KeyRelease.  Turning this on will trigger a Scam warning about running custom scripts."] = "This option hides text error popups and dialogs and stack traces ingame.  This is the equivalent of /script UIErrorsFrame:Hide() in a KeyRelease.  Turning this on will trigger a Scam warning about running custom scripts."
L["This option hides text error popups and dialogs and stack traces ingame.  This is the equivalent of /script UIErrorsFrame:Hide() in a PostMacro.  Turning this on will trigger a Scam warning about running custom scripts."] = "This option hides text error popups and dialogs and stack traces ingame.  This is the equivalent of /script UIErrorsFrame:Hide() in a PostMacro.  Turning this on will trigger a Scam warning about running custom scripts."
L["This option prevents macros firing unless you have a target. Helps reduce mistaken targeting of other mobs/groups when your target dies."] = "This option prevents macros firing unless you have a target. Helps reduce mistaken targeting of other mobs/groups when your target dies."
L["This Sequence is currently Disabled Locally."] = "This Sequence is currently Disabled Locally."
L["This version has been modified by TimothyLuke to make the power of GnomeSequencer avaialble to people who are not comfortable with lua programming."] = "This version has been modified by TimothyLuke to make the power of GnomeSequencer avaialble to people who are not comfortable with lua programming."
L["This will display debug messages for the "] = "This will display debug messages for the "
L["This will display debug messages for the Core of GS-E"] = "This will display debug messages for the Core of GS-E"
L["This will display debug messages for the GS-E Ingame Transmission and transfer"] = "This will display debug messages for the GS-E Ingame Transmission and transfer"
L["This will display debug messages for the GS-E Sequence Editor"] = "This will display debug messages for the GS-E Sequence Editor"
L["This will display debug messages for the GS-E Translator"] = "This will display debug messages for the GS-E Translator"
L["This will display debug messages in the Chat window."] = "This will display debug messages in the Chat window."
L["Title Colour"] = "Title Colour"
L["To get started "] = "To get started "
L["To use a macro, open the macros interface and create a macro with the exact same name as one from the list.  A new macro with two lines will be created and place this on your action bar."] = "To use a macro, open the macros interface and create a macro with the exact same name as one from the list.  A new macro with two lines will be created and place this on your action bar."
L["Translate to"] = "Translate to"
L["Translated Sequence"] = "Translated Sequence"
L["Trinket 1"] = "Trinket 1"
L["Trinket 2"] = "Trinket 2"
L["Two sequences with unknown sources found."] = "Two sequences with unknown sources found."
L["Unknown Author|r "] = "Unknown Author|r "
L["Unknown Colour"] = "Unknown Colour"
L["Update"] = "Update"
L["Updating due to new version."] = "Updating due to new version."
L["Use"] = "Use"
L["Use Belt Item in KeyRelease"] = "Use Belt Item in KeyRelease"
L["Use Belt Item in Postmacro"] = "Use Belt Item in Postmacro"
L["Use First Ring in KeyRelease"] = "Use First Ring in KeyRelease"
L["Use First Ring in Postmacro"] = "Use First Ring in Postmacro"
L["Use First Trinket in KeyRelease"] = "Use First Trinket in KeyRelease"
L["Use First Trinket in Postmacro"] = "Use First Trinket in Postmacro"
L["Use Global Account Macros"] = "Use Global Account Macros"
L["Use Head Item in KeyRelease"] = "Use Head Item in KeyRelease"
L["Use Head Item in Postmacro"] = "Use Head Item in Postmacro"
L["Use Macro Translator"] = "Use Macro Translator"
L["Use Neck Item in KeyRelease"] = "Use Neck Item in KeyRelease"
L["Use Neck Item in Postmacro"] = "Use Neck Item in Postmacro"
L["Use Realtime Parsing"] = "Use Realtime Parsing"
L["Use Second Ring in KeyRelease"] = "Use Second Ring in KeyRelease"
L["Use Second Ring in Postmacro"] = "Use Second Ring in Postmacro"
L["Use Second Trinket in KeyRelease"] = "Use Second Trinket in KeyRelease"
L["Use Second Trinket in Postmacro"] = "Use Second Trinket in Postmacro"
L["Version="] = "Version="
L["We have a perfect match"] = "We have a perfect match"
L["When creating a macro, if there is not a personal character macro space, create an account wide macro."] = "When creating a macro, if there is not a personal character macro space, create an account wide macro."
L["When loading or creating a sequence, if it is a global or the macro has an unknown specID automatically create the Macro Stub in Account Macros"] = "When loading or creating a sequence, if it is a global or the macro has an unknown specID automatically create the Macro Stub in Account Macros"
L["When loading or creating a sequence, if it is a macro of the same class automatically create the Macro Stub"] = "When loading or creating a sequence, if it is a macro of the same class automatically create the Macro Stub"
L["with no body"] = "with no body"
L["Yes"] = "Yes"
L["You cannot delete the Default version of this macro.  Please choose another version to be the Default on the Configuration tab."] = "You cannot delete the Default version of this macro.  Please choose another version to be the Default on the Configuration tab."
L["You cannot delete this version of a sequence.  This version will be reloaded as it is contained in "] = "You cannot delete this version of a sequence.  This version will be reloaded as it is contained in "
L["You need to reload the User Interface for the change in StepFunction to take effect.  Would you like to do this now?"] = "You need to reload the User Interface for the change in StepFunction to take effect.  Would you like to do this now?"
L["You need to reload the User Interface to complete this task.  Would you like to do this now?"] = "You need to reload the User Interface to complete this task.  Would you like to do this now?"
L["Your current Specialisation is "] = "Your current Specialisation is "




L["Update"] = true
L["<SEQUENCEDEBUG> |r "] = true
L["<DEBUG> |r "] = true

--Output Strings from Core
L["Close to Maximum Personal Macros.|r  You can have a maximum of "] = true
L[" macros per character.  You currently have "] = true
L["|r.  As a result this macro was not created.  Please delete some macros and reenter "] = true
L["/gs|r again."] = true
L["Close to Maximum Macros.|r  You can have a maximum of "] = true
L["|r.  You can also have a  maximum of "] = true
L[" macros per Account.  You currently have "] = true
L["Contributed by: "] = true
L["No Help Information "] = true
L["Unknown Author|r "] = true
L["|r Incomplete Sequence Definition - This sequence has no further information "] = true
L["Two sequences with unknown sources found."] = true
L["FYou cannot delete this version of a sequence.  This version will be reloaded as it is contained in "] = true

-- Setup and Help Output from Core
L["GnomeSequencer was originally written by semlar of wowinterface.com."] = true
L["This is a small addon that allows you create a sequence of macros to be executed at the push of a button."] = true
L["Like a /castsequence macro, it cycles through a series of commands when the button is pushed. However, unlike castsequence, it uses macro text for the commands instead of spells, and it advances every time the button is pushed instead of stopping when it can't cast something."] = true
L["This version has been modified by TimothyLuke to make the power of GnomeSequencer avaialble to people who are not comfortable with lua programming."] = true
L[":|r To get started "] = true
L["/gs|r will list any macros available to your spec.  This will also add any macros available for your current spec to the macro interface."] = true
L["/gs listall|r will produce a list of all available macros with some help information."] = true
L["To use a macro, open the macros interface and create a macro with the exact same name as one from the list.  A new macro with two lines will be created and place this on your action bar."] = true
L["The command "] = true
L["/gs showspec|r will show your current Specialisation and the SPECID needed to tag any existing macros."] = true
L["/gs cleanorphans|r will loop through your macros and delete any left over GS-E macros that no longer have a sequence to match them."] = true
L[":|r Your current Specialisation is "] = true
L["  The Alternative ClassID is "] = true
L["GnomeSequencer-Enhanced loaded.|r  Type "] = true
L["/gs help|r to get started."] = true
L["Version="] = true
L[":|r You cannot delete the only copy of a sequence."] = true
L[" has been added as a new version and set to active.  Please review if this is as expected."] = true
L["A sequence collision has occured. "] = true
L[" tried to overwrite the version already loaded from "] = true
L[". This version was not loaded."] = true
L["Sequence specID set to current spec of "] = true
L["Sequence Author set to Unknown"] = true
L["No Help Information Available"] = true
L[" was imported with the following errors."] = true

-- 1.4 changes
L["No Active Version"] = true
L["Matching helpTxt"] = true
L["Different helpTxt"] = true
L["You cannot delete this version of a sequence.  This version will be reloaded as it is contained in "] = true

--sequence editor stuff
L["Sequence"] = true
L["Edit"] = true
L["New"] = true
L["Choose Language"] = true
L["Translated Sequence"] = true
L["Sequence Viewer"] = true
L["Gnome Sequencer: Sequence Viewer"] = true
L["Load Sequence"] = true
L["Disable Sequence"] = true
L["Enable Sequence"] = true
L["Translate to"] = true
L["Sequence Editor"] = true
L["Gnome Sequencer: Sequence Editor."] = true
L["Sequence Name"] = true
L["Step Function"] = true
L["Sequential (1 2 3 4)"] = true
L["Priority List (1 12 123 1234)"] = true
L["Specialization Specific Macro"] = true
L["Classwide Macro"] = true
L["Macro Icon"] = true
L["KeyPress"] = true
L["KeyRelease"] = true
L["Completely New GS Macro."] = true
L["Please wait till you have left combat before using the Sequence Editor."] = true
L["The Sequence Editor is an addon for GnomeSequencer-Enhanced that allows you to view and edit Sequences in game.  Type "] = true
L["/gs |r to get started."] = true
L["Gnome Sequencer: Sequence Version Manager"] = true
L["Manage Versions"] = true
L["Active Version: "] = true
L["Select Other Version"] = true
L["Make Active"] = true
L["Delete Version"] = true
L["No Sequences present so none displayed in the list."] = true
L["Specialisation / Class ID"] = true
L["You need to reload the User Interface for the change in StepFunction to take effect.  Would you like to do this now?"] = true
-- options Debug


-- options stuff
L["You need to reload the User Interface to complete this task.  Would you like to do this now?"] = true
L["Yes"] = true
L["No"] = true
L["|cffff0000GS-E:|r Gnome Sequencer - Enhanced Options"] = true
L["General"] = true
L["General Options"] = true
L["Only Save Local Macros"] = true
L["GS-E can save all macros or only those versions that you have created locally.  Turning this off will cache all macros in your WTF\\GS-Core.lua variables file but will increase load times and potentially cause colissions."] = true
L["Use Macro Translator"] = true
L["The Macro Translator will translate an English sequence to your local language for execution.  It can also be used to translate a sequence into a different language.  It is also used for syntax based colour markup of Sequences in the editor."] = true
L["Delete Orphaned Macros on Logout"] = true
L["As GS-E is updated, there may be left over macros that no longer relate to sequences.  This will check for these automatically on logout.  Alternatively this check can be run via /gs cleanorphans"] = true
L["Use Global Account Macros"] = true
L["When creating a macro, if there is not a personal character macro space, create an account wide macro."] = true
L["Set Default Icon QuestionMark"] = true
L["By setting the default Icon for all macros to be the QuestionMark, the macro button on your toolbar will change every key hit."] = true
L["Seed Initial Macro"] = true
L["If you load Gnome Sequencer - Enhanced and the Sequence Editor and want to create new macros from scratch, this will enable a first cut sequenced template that you can load into the editor as a starting point.  This enables a Hello World macro called Draik01.  You will need to do a /console reloadui after this for this to take effect."] = true
L["Gameplay Options"] = true
L["Require Target to use"] = true
L["This option prevents macros firing unless you have a target. Helps reduce mistaken targeting of other mobs/groups when your target dies."] = true
L["Prevent Sound Errors"] = true
L["This option hide error sounds like \"That is out of range\" from being played while you are hitting a GS Macro.  This is the equivalent of /console Sound_EnableErrorSpeech lines within a Sequence.  Turning this on will trigger a Scam warning about running custom scripts."] = true
L["Prevent UI Errors"] = true
L["This option hides text error popups and dialogs and stack traces ingame.  This is the equivalent of /script UIErrorsFrame:Hide() in a KeyRelease.  Turning this on will trigger a Scam warning about running custom scripts."] = true
L["Clear Errors"] = true
L["This option clears errors and stack traces ingame.  This is the equivalent of /run UIErrorsFrame:Clear() in a KeyRelease.  Turning this on will trigger a Scam warning about running custom scripts."] = true
L["Use First Ring in KeyRelease"] = true
L["Incorporate the first ring slot into the KeyRelease. This is the equivalent of /use [combat] 11 in a KeyRelease."] = true
L["Use Second Ring in KeyRelease"] = true
L["Incorporate the second ring slot into the KeyRelease. This is the equivalent of /use [combat] 12 in a KeyRelease."] = true
L["Use First Trinket in KeyRelease"] = true
L["Incorporate the first trinket slot into the KeyRelease. This is the equivalent of /use [combat] 13 in a KeyRelease."] = true
L["Use Second Trinket in KeyRelease"] = true
L["Incorporate the second trinket slot into the KeyRelease. This is the equivalent of /use [combat] 14 in a KeyRelease."] = true
L["Use Neck Item in KeyRelease"] = true
L["Incorporate the neck slot into the KeyRelease. This is the equivalent of /use [combat] 2 in a KeyRelease."] = true
L["Use Belt Item in KeyRelease"] = true
L["Incorporate the belt slot into the KeyRelease. This is the equivalent of /use [combat] 5 in a KeyRelease."] = true
L["Debug Mode Options"] = true
L["Enable Mod Debug Mode"] = true
L["This option dumps extra trace information to your chat window to help troubleshoot problems with the mod"] = true
L["Display debug messages in Chat Window"] = true
L["This will display debug messages in the Chat window."] = true
L["Store Debug Messages"] = true
L["Store output of debug messages in a Global Variable that can be referrenced by other mods."] = true
L["Debug Sequence Execution"] = true
L["Output the action for each button press to verify StepFunction and spell availability."] = true
L["Colour"] = true
L["Colour and Accessibility Options"] = true
L["Title Colour"] = true
L["Picks a Custom Colour for the Mod Names."] = true
L["Author Colour"] = true
L["Picks a Custom Colour for the Author."] = true
L["Command Colour"] = true
L["Picks a Custom Colour for the Commands."] = true
L["Emphasis Colour"] = true
L["Picks a Custom Colour for emphasis."] = true
L["Normal Colour"] = true
L["Picks a Custom Colour to be used normally."] = true
L["Editor Colours"] = true
L["Spell Colour"] = true
L["Picks a Custom Colour to be used for Spells and Abilities."] = true
L["Unknown Colour"] = true
L["Picks a Custom Colour to be used for unknown terms."] = true
L["Icon Colour"] = true
L["Picks a Custom Colour to be used for Icons."] = true
L["SpecID/ClassID Colour"] = true
L["Picks a Custom Colour to be used for numbers."] = true
L["String Colour"] = true
L["Picks a Custom Colour to be used for strings."] = true
L["Conditionals Colour"] = true
L["Picks a Custom Colour to be used for macro conditionals eg [mod:shift]"] = true
L["Help Colour"] = true
L["Picks a Custom Colour to be used for braces and indents."] = true
L["Step Functions"] = true
L["Picks a Custom Colour to be used for StepFunctions."] = true
L["Language Colour"] = true
L["Picks a Custom Colour to be used for language descriptors"] = true
L["Blizzard Functions Colour"] = true
L["Picks a Custom Colour to be used for Macro Keywords like /cast and /target"] = true
L["Plugins"] = true
L["GS-E Plugins"] = true
L["Registered Addons"] = true
L["Available Addons"] = true
L[":|r The Sequence Translator allows you to use GS-E on other languages than enUS.  It will translate sequences to match your language.  If you also have the Sequence Editor you can translate sequences between languages.  The GS-E Sequence Translator is available on curse.com"] = true
L["Use Realtime Parsing"] = true
L["The Sequence Editor can attempt to parse the Sequences, KeyPress and KeyRelease in realtime.  This is still experimental so can be turned off."] = true
L["Import"] = true
L["Close"] = true
L["Import Macro from Forums"] = true
L["Debug Output Options"] = true
L["Enable Debug for the following Modules"] = true
L["Debug"] = true
L["Filter Macro Selection"] = true
L["Show All Macros in Editor"] = true
L["By setting this value the Sequence Editor will show every macro for every class."] = true
L["Show Class Macros in Editor"] = true
L["By setting this value the Sequence Editor will show every macro for your class."] = true
L["Source Language "] = true
L[" is not available.  Unable to translate sequence "] = true
L["Target language "] = true
L["Auto Create Class Macro Stubs"] = true
L["When loading or creating a sequence, if it is a macro of the same class automatically create the Macro Stub"] = true
L["Auto Create Global Macro Stubs"] = true
L["When loading or creating a sequence, if it is a global or the macro has an unknown specID automatically create the Macro Stub in Account Macros"] = true
L["Updating due to new version."] = true
L["Creating New Sequence."] = true

-- Transmission stuff
L["This will display debug messages for the GS-E Ingame Transmission and transfer"] = true

-- New Strings 1.4
L["Use Head Item in KeyRelease"] = true
L["Incorporate the Head slot into the KeyRelease. This is the equivalent of /use [combat] 1 in a KeyRelease."] = true
L["GS-E: Left Click to open the Sequence Editor"] = true
L["GS-E: Middle Click to open the Transmission Interface"] = true
L["GS-E: Right Click to open the Sequence Debugger"] = true
L["Sequence Debugger"] = true
L["Gnome Sequencer: Sequence Debugger. Monitor the Execution of your Macro"] = true
L["Output"] = true
L["Pause"] = true
L["Resume"] = true
L["Clear"] = true
L["Options"] = true
L["Disable"] = true
L["Enable"] = true
L["GnomeSequencer-Enhanced"] = true
L["Help Information"] = true
L["Save"] = true
L["Sequence Saved as version "] = true
L["Imported new sequence "] = true
L["Send To"] = true
L["Send"] = true
L["Received Sequence "] = true
L[" from "] = true
L[" saved as version "] = true
L["Ready to Send"] = true
L[" sent"] = true
L["Reset Macro when out of combat"] = true
L["Resets macros back to the initial state when out of combat."] = true
L["A sequence collision has occured.  Your local version of "] = true

-- 1.4.4
L["Inner Loop Start"] = true
L["Inner Loop End"] = true
L["Inner Loop Limit"] = true
L["Record Macro"] = true
L["Gnome Sequencer: Record your rotation to a macro."] = true
L["Actions"] = true
L["Record"] = true
L["Pause"] = true
L["Create Macro"] = true
L["Stop"] = true

-- 2.0
L["The Custom StepFunction Specified is not recognised and has been ignored."] = true
L["Load"] = true
L["There are No Macros Loaded for this class.  Would you like to load the Sample Macro?"]= true
L["A sequence collision has occured.  Extra versions of this macro have been loaded.  Manage the sequence to determine how to use them "] = true
L["GSE is out of date. You can download the newest version from https://mods.curse.com/addons/wow/gnomesequencer-enhanced."] = true
L["Macro unable to be imported."] = true
L["Macro Import Successful."]= true
L["Gnome Sequencer: Import a Macro String."] = true
L["GSE Macro"] = true
L["Legacy GS/GSE1 Macro"] = true
L["Macro Collection to Import."] = true
L["Configuration"] = true
L["Talents"] = true
L["Help Information"] = true
L["Help Link"] = true
L["Default Version"] = true
L["Raid"] = true
L["Mythic"] = true
L["PVP"] = true
L["Language"] = true
L["PreMacro"] = true
L["PostMacro"] = true
L["Author"] = true
L["Head"] = true
L["Neck"] = true
L["Belt"] = true
L["Ring 1"] = true
L["Ring 2"] = true
L["Trinket 1"] = true
L["Trinket 2"] = true
L["Use"] = true
L["Target"] = true
L["Combat"] = true
L["Resets"] = true
L["Sequence %s saved."] = true
L["This is the only version of this macro.  Delete the entire macro to delete this version."] = true
L["You cannot delete the Default version of this macro.  Please choose another version to be the Default on the Configuration tab."] = true
L["Macro Version %d deleted."] = true
L["This change will not come into effect until you save this macro."] = true
L["PVP setting changed to Default."] = true
L["Are you sure you want to delete %s?  This will delete the macro and all versions.  This action cannot be undone."] = true
L["Delete"] = true
L["Cancel"] = true
L["Delete Icon"] = true
L["Create Icon"] = true
L["Addin Version %s contained versions for the following macros: \n%s"] = true
L["GSE allows plugins to load Macro Collections as plugins.  You can reload a collection by pressing the button below."] = true
L["The Sample Macros have been reloaded."] = true
L["GSE is out of date. You can download the newest version from https://mods.curse.com/addons/wow/gnomesequencer-enhanced."] = true
L["GSE"] = true
L["/gs |r to get started."] = true
L["Gnome Sequencer: Export a Sequence String."] = true
L["Export a Sequence"] = true
L["Export"] = true
L["Help URL"] = true
L["Copy this link and open it in a Browser."] = true
L["This will display debug messages for the "] = true
L[" Deleted Orphaned Macro "] = true
