
if not(GetLocale() == "ptBR") then
    return;
end

local L = LibStub("AceLocale-3.0"):NewLocale("GSE", "ptBR", true)

-- Options translation
L["  The Alternative ClassID is "] = "  O ClassID alternativa é "
L[" already exists."] = "Já existente"
L[" equals "] = "é igual a"
L[" equals currentclassid "] = "É igual a ID de classe atual"
L[" from "] = "de"
L[" From library"] = "da biblioteca"
L[" has been added as a new version and set to active.  Please review if this is as expected."] = "foi adicionado como uma nova versão e definido como ativo. Por favor, verifique se isso é como esperado."
L[" is not available.  Unable to translate sequence "] = "não está disponível. Incapaz de traduzir sequência"
L[" is unknown."] = "é desconhecido"
L[" macros per Account.  You currently have "] = "Macros por conta. Você já as tem atualmente"
L[" macros per character.  You currently have "] = "macros por personagem. Você já as tem atualmente"
L[" not added to list."] = "Não adicionado a lista."
L[" saved as version "] = "salva como versão"
L[" sent"] = "enviado"
L[" Sequence named "] = "seqüência nomeada"
L[" tried to overwrite the version already loaded from "] = "você tentou substituir uma versão que já foi carregada."
L[" was imported with the following errors."] = "foi importado com os seguintes erros"
L[" with iconid "] = "com o ícone ID"
L[". Overriding with information for current spec "] = "As informações foram substituídas para a especialização atual"
L[". This version was not loaded."] = "Esta versão não pode ser carregada."
L["/gs |r to get started."] = "/gs |r está iniciando."
L["/gs cleanorphans|r will loop through your macros and delete any left over GS-E macros that no longer have a sequence to match them."] = [=[
/ Gs cleanorphans | r fará um loop em suas macros e excluirá qualquer macros do GS-E que não têm uma sequência para combiná-los.]=]
L["/gs help|r to get started."] = "/gs help|r para iniciar."
L["/gs listall|r will produce a list of all available macros with some help information."] = "/gs listall|r irá produzir uma lista com todas as macros disponíveis com algumas informações de ajuda."
L["/gs showspec|r will show your current Specialisation and the SPECID needed to tag any existing macros."] = "/ Gs showspec | r irá mostrar a sua especialização atual eo SPECID necessário para marcar quaisquer macros existentes"
L["/gs|r again."] = "/gs|r novamente"
L["/gs|r will list any macros available to your spec.  This will also add any macros available for your current spec to the macro interface."] = "/ Gs | r irá listar todos os macros disponíveis para a sua especialização. Isso também irá adicionar quaisquer macros disponíveis para sua especificação atual para a interface macro."
L["/gsse |r to get started."] = "/gsse |r para iniciar"
L[":|r The Sequence Translator allows you to use GS-E on other languages than enUS.  It will translate sequences to match your language.  If you also have the Sequence Editor you can translate sequences between languages.  The GS-E Sequence Translator is available on curse.com"] = ": | R The Translator Sequence permite que você use GS-E em outros idiomas além do enUS. Ele irá traduzir sequências para combinar seu idioma. Se você também tem a Sequence Editor você pode traduzir sequências entre as línguas. O GS-E Sequence Translator é acessível em curse.com"
L[":|r To get started "] = ":|r para iniciar"
L[":|r You cannot delete the only copy of a sequence."] = "Você não pode excluir a única cópia de uma sequência."
L[":|r Your current Specialisation is "] = ":|r Sua especialização atual é "
L["[GNOME] syntax error on line %d of Sequences.lua:|r %s"] = "[GNOME] erro de sintaxe na linha %d of Sequences.lua:|r %s"
L["], (GSisEmpty(GSMasterOptions.SequenceLibrary["] = "], (GSisEmpty(GSMasterOptions.SequenceLibrary["
L["].lang or GetLocale()), key)"] = "].lang or GetLocale()), key)"
L["A sequence colision has occured. "] = "Ocorreu um erro de colisão na sequência."
L["A sequence collision has occured. "] = "Ocorreu um erro de colisão na sequência."
L["A sequence collision has occured.  Extra versions of this macro have been loaded.  Manage the sequence to determine how to use them "] = "Ocorreu uma colisão de sequência. Versões extras desta macro foram carregadas. Gerencie a seqüência para determinar como usá-las."
L["A sequence collision has occured.  Your local version of "] = "Ocorreu uma colisão na sequência. Sua versão local é"
L["Actions"] = "Ações"
L["Active Version "] = "Versão Ativa"
L["Active Version: "] = "Versão Ativa:"
L[ [=[Addin Version %s contained versions for the following macros: 
%s]=] ] = [=[A versão incluída % s continha versões para as seguintes macros:
%s]=]
L["Adding missing Language :"] = "Ausência de Linguagem Adicionada"
L["Are you sure you want to delete %s?  This will delete the macro and all versions.  This action cannot be undone."] = "Tem certeza de que deseja excluir % s? Isso excluirá a macro e todas as versões. Essa ação não poderá ser desfeita."
L["Author"] = "Autor"
L["Author Colour"] = "Cor do Autor"
L["Available Addons"] = "Addons Disponíveis"
L["Belt"] = "Cinto"
L["Blizzard Functions Colour"] = "Funções de Cores da Blizzard"
L["Cancel"] = "Cancelar"
L["Class = "] = "Classe ="
L["Clear"] = "Limpar"
L["Clear Errors"] = "Limpar Erros"
L["Close"] = "Fechar"
L["Combat"] = "Combate"
L["Command Colour"] = "Cor do Comando"
L["Completely New GS Macro."] = "Nova GS Macro Finalizada."
L["Conditionals Colour"] = "Cor Condicional"
L["Configuration"] = "Configuração"
L["Contributed by: "] = "Contribuição de:"
L["Create Icon"] = "Criar Ícone"
L["Create Macro"] = "Criar Macro"
L["Debug"] = "Depurar"
L["Delete"] = "Deletar"
L["Delete Icon"] = "Deletar  Ícone"
L["Disable"] = "Desabilitar"
L["Disable Sequence"] = "Desabilitar seqüência"
L["Edit"] = "Editar"
L["Editor Colours"] = "Editor de Cores"
L["Enable"] = "Habilitar"
L["Export"] = "Exportar"
L["General"] = "Geral"
L["General Options"] = "Opções Gerais"
L["GnomeSequencer-Enhanced loaded.|r  Type "] = "GnomeSequencer-Enhanced carregado.|r  Digitar "
L["Head"] = "Cabeça"
L["Help Colour"] = "Ajuda de Cores"
L["Help Information"] = "Informações de Ajuda"
L["Help Link"] = "Link de Ajuda"
L["Help URL"] = "Ajuda URL"
L["I am loaded"] = "Eu estou Carregando."
L["Icon Colour"] = "Cor do Ícone"
L["Icon: "] = "Ícone:"
L["Import"] = "Importar"
L["Line : "] = "Linha :"
L["Load"] = "Carregar"
L["Load Sequence"] = "Carregar Seqüência"
L["Mythic"] = "Mítico"
L["Neck"] = "Colar"
L["New"] = "Novo"
L["No"] = "Não"
L["No Active Version"] = "Versão não ativada."
L["No Help Information "] = "Sem Informações de Ajuda"
L["No Help Information Available"] = "Sem Informações de Ajuda Disponíveis"
L["none"] = "Não"
L["Options"] = "Opções"
L["Output"] = "Saída"
L["Pause"] = "Pausa"
L["Raid"] = "Raide"
L["Received Sequence "] = "Seqüência Recebida"
L["Record"] = "Gravada"
L["Record Macro"] = "Macro Gravada"
L["Registered Addons"] = "Addons Registrados"
L["Reloading Sequences"] = "Carregando Seqüências"
L["Removing "] = "Removendo"
L["Resets"] = "Reiniciar"
L["Resume"] = "Resumo"
L["Ring 1"] = "Anel 1"
L["Ring 2"] = "Anel 2"
L["Save"] = "Salvar"
L["Send"] = "Enviar"
L["Send To"] = "Enviar Para"
L["Sequence"] = "Seqüência"
L["Stop"] = "Parar"
L["Talents"] = "Talentos"
L["Target"] = "Alvo"
L["Target language "] = "Linguagem do Alvo"
L["Testing "] = "Testando"
L["Trinket 1"] = "Berloque 1"
L["Trinket 2"] = "Berloque 2"
L["Use"] = "Usar"
L["Version="] = "Versão="
L["Yes"] = "Sim"


