if not(GetLocale() == "frFR") then
    return;
end

local L = WeakAuras.L

-- Options translation
-- L["Ability Charges"] = ""
L["Add Triggers"] = "Ajouter Déclencheur"
L["Always Active"] = "Toujours actif"
L["- Any"] = "- N'importe"
L["Back"] = "Retour"
L["Bleed"] = "Saignement"
L["BloodLust/Heroism"] = "Héroïsme/Furie sanguinaire"
L["buff"] = "amélioration"
L["Buff"] = "Amélioration"
L["Buffs"] = "Améliorations"
L["Cancel"] = "Annuler"
L["Cast"] = "Incantation"
L[" (Channeling)"] = "(Canalisé)"
L["cooldown"] = "recharge"
L["Cooldowns"] = "Recharges"
L["Crimson Vial Item Count"] = "Nombre de Fioles cramoisies"
L["- Deathknight 2P Bonus"] = "- Chevalier de la Mort Bonus 2P"
L["- Deathknight Unholy 4P Bonus"] = "- Chevalier de la Mort Impie Bonus 4P"
L["debuff"] = "affaiblissement"
L["Debuffs"] = "Affaiblissements"
L["Enchants"] = "Enchantements"
L["General"] = "Général"
L[" (Healing received increase)"] = "(Soins reçus augmentés)"
L["Health"] = "Santé"
L["- Holy Word: Chastise"] = "- Mot sacré : Châtier"
L["- Holy Word: Sanctify"] = "- Mot sacré : Sanctification"
L["- Holy Word: Serenity"] = "- Mot sacré : Sérénité"
L["Keeps existing triggers intact"] = "Garder intact les déclencheurs existants"
L["Legendaries"] = "Légendaires"
L["- Monk Windwalker 4P Bonus"] = "- Moine Marche-Vent Bonus 4P"
L["Nimble Brew Item Count"] = "Nombre de Breuvages de vivacité"
L["- Paladin Protection 2P Bonus"] = "- Paladin Protection Bonus 2P"
L["- Paladin Retribution 2P Bonus"] = "- Paladin Vindicte Bonus 2P"
L["- Paladin T19 Retribution 4P Bonus"] = "- Paladin Vindicte T19 Bonus 4P"
L["(Pet)"] = "(Familier)"
L["Pet alive"] = "Familier vivant"
L["Pet Behavior"] = "Comportement du Familier"
L["PVP Set"] = "Ensemble JcJ"
L["PvP Talents"] = "Talents JcJ"
L["PVP Trinkets"] = "Bijou JcJ"
L["Replace all existing triggers"] = "Remplacer tous les déclencheurs existant"
L["Replace Triggers"] = "Remplacer les déclencheurs"
L["Resources"] = "Ressources"
L["Resources and Shapeshift Form"] = "Ressources et Forme de Changeforme"
L["- Rogue Assassination/Outlaw 4P Bonus"] = "- Voleur Assassinat/Hors-la-loi Bonus 4P"
L["- Rogue Subtlety 4P Bonus"] = "- Voleur Finesse Bonus 4P"
L["- Rogue T19 Outlaw 4P Bonus"] = "- Voleur Hors-la-loi T19 Bonus 4P"
L["Rooted"] = "Enraciné"
L["Runes"] = "Runes"
L["- Shaman Elemental 4P Bonus"] = "- Chaman Élémentaire Bonus 4P"
L["- Shaman Enhancement 2P Bonus"] = "- Chaman Amélioration Bonus 2P"
L["Shapeshift Form"] = "Forme de Changeforme"
L["Slowed"] = "Ralenti"
L["Stagger"] = "Report"
L["Stun"] = "Étourdi"
L["T19 Damage Trinkets"] = "Bijou de dégâts T19"
L["- T19 Druid Guardian 4P Bonus"] = "- Druide Gardien T19 Bonus 4P"
L["T19 Healer Trinkets"] = "Bijou de soin T19"
L["T19 Sets"] = "Ensembles T19"
L["T19 Tank Trinkets"] = "Bijou de tanks T19"
L["Totem"] = "Totem"
L["Totems"] = "Totems"
L["Unknown Item"] = "Objet inconnu"
L["Unknown Spell"] = "Sort inconnu"
L["- Warlock Affliction 4P/Demonology 2P Bonus"] = "- Démoniste Affliction 4P/Démonologie 2P"
L["- Warlock T19 Destruction 4P Bonus"] = "- Démoniste Destruction T19 Bonus 4P"
L["- Warrior 2P Bonus"] = "- Guerrier Bonus 2P"
L["- Warrior T19 Fury 2P Bonus"] = "- Guerrier Fureur T19 Bonus 2P"
L["(Water Elemental)"] = "(Élémentaire d'eau)"



