if not(GetLocale() == "koKR") then
    return;
end

local L = WeakAuras.L

-- Options translation
L["Ability Charges"] = "기술 충전"
L["Add Triggers"] = "활성 조건 추가"
L["Always Active"] = "항상 활성화"
L["- Any"] = "- 모두"
L["Back"] = "뒤로"
L["Bleed"] = "출혈"
L["BloodLust/Heroism"] = "피의 욕망/영웅심"
L["buff"] = "강화 효과"
L["Buff"] = "강화 효과"
L["Buffs"] = "강화 효과"
L["Cancel"] = "취소"
L["Cast"] = "시전"
L[" (Channeling)"] = " (정신 집중)"
L["cooldown"] = "재사용 대기시간"
L["Cooldowns"] = "재사용 대기시간"
L["Crimson Vial Item Count"] = "진홍색 약병 아이템 개수"
L["- Deathknight 2P Bonus"] = "- 죽음의 기사 2세트 효과"
L["- Deathknight Unholy 4P Bonus"] = "- 부정 죽음의 기사 4세트 효과"
L["debuff"] = "약화 효과"
L["Debuffs"] = "약화 효과"
L["Enchants"] = "마법 부여"
L["General"] = "일반"
L[" (Healing received increase)"] = " (받는 치유 증가)"
L["Health"] = "생명력"
L["- Holy Word: Chastise"] = "- 빛의 권능: 응징"
L["- Holy Word: Sanctify"] = "- 빛의 권능: 신성화"
L["- Holy Word: Serenity"] = "- 빛의 권능: 평온"
L["Keeps existing triggers intact"] = "활성 조건 그대로 유지"
L["Legendaries"] = "전설"
L["- Monk Windwalker 4P Bonus"] = "- 풍운 수도사 4세트 효과"
L["Nimble Brew Item Count"] = "민활주 아이템 개수"
L["- Paladin Protection 2P Bonus"] = "- 보호 성기사 2세트 효과"
L["- Paladin Retribution 2P Bonus"] = "- 징벌 성기사 2세트 효과"
L["- Paladin T19 Retribution 4P Bonus"] = "- 성기사 T19 징벌 4세트 효과"
L["(Pet)"] = "(소환수)"
L["Pet alive"] = "소환수 생존"
L["Pet Behavior"] = "소환수 행동"
L["PVP Set"] = "PVP 세트"
L["PvP Talents"] = "명예 특성"
L["PVP Trinkets"] = "PVP 장신구"
L["Replace all existing triggers"] = "모든 활성 조건 대체"
L["Replace Triggers"] = "대체 활성 조건"
L["Resources"] = "자원"
L["Resources and Shapeshift Form"] = "자원과 태세 변환"
L["- Rogue Assassination/Outlaw 4P Bonus"] = "- 암살/무법 도적 4세트 효과"
L["- Rogue Subtlety 4P Bonus"] = "- 잠행 도적 4세트 효과"
L["- Rogue T19 Outlaw 4P Bonus"] = "- 도적 T19 무법 4세트 효과"
L["Rooted"] = "묶임"
L["Runes"] = "룬"
L["- Shaman Elemental 4P Bonus"] = "- 정기 주술사 4세트 효과"
L["- Shaman Enhancement 2P Bonus"] = "- 고양 주술사 2세트 효과"
L["Shapeshift Form"] = "태세 변환"
L["Slowed"] = "느려짐"
L["Stagger"] = "시간차"
L["Stun"] = "기절"
L["T19 Damage Trinkets"] = "T19 딜러 장신구"
L["- T19 Druid Guardian 4P Bonus"] = "- T19 수호 드루이드 4세트 효과"
L["T19 Healer Trinkets"] = "T19 힐러 장신구"
L["T19 Sets"] = "T19 세트"
L["T19 Tank Trinkets"] = "T19 탱커 장신구"
L["Totem"] = "토템"
L["Totems"] = "토템"
L["Unknown Item"] = "알 수 없는 아이템"
L["Unknown Spell"] = "알 수 없는 주문"
L["- Warlock Affliction 4P/Demonology 2P Bonus"] = "- 흑마법사 고통 4세트/악마 2세트 효과"
L["- Warlock T19 Destruction 4P Bonus"] = "- 흑마법사 T19 파괴 4세트 효과"
L["- Warrior 2P Bonus"] = "- 전사 2세트 효과"
L["- Warrior T19 Fury 2P Bonus"] = "- 전사 T19 분노 2세트 효과"
L["(Water Elemental)"] = "(물 정령)"



