if not(GetLocale() == "deDE") then
    return;
end

local L = WeakAuras.L

-- Options translation
-- L["Ability Charges"] = ""
L["Add Triggers"] = "Auslöser hinzufügen"
L["Always Active"] = "Immer aktiv"
-- L["- Any"] = ""
L["Back"] = "Zurück"
-- L["Bleed"] = ""
L["BloodLust/Heroism"] = "Kampfrausch/Heldentum"
L["buff"] = "Stärkungszauber"
L["Buff"] = "Stärkungszauber"
L["Buffs"] = "Stärkungszauber"
L["Cancel"] = "Abbrechen"
L["Cast"] = "Zauberwirken"
-- L[" (Channeling)"] = ""
L["cooldown"] = "Abklingzeit"
L["Cooldowns"] = "Abklingzeiten"
-- L["Crimson Vial Item Count"] = ""
-- L["- Deathknight 2P Bonus"] = ""
-- L["- Deathknight Unholy 4P Bonus"] = ""
L["debuff"] = "Schwächungszauber"
L["Debuffs"] = "Schwächungszauber"
L["Enchants"] = "Verzauberungen"
L["General"] = "Allgemein"
L[" (Healing received increase)"] = " (erhaltene Heilung erhöht)"
L["Health"] = "Gesundheit"
L["- Holy Word: Chastise"] = "- Segenswort: Züchtigung"
-- L["- Holy Word: Sanctify"] = ""
-- L["- Holy Word: Serenity"] = ""
L["Keeps existing triggers intact"] = "Verändert existierende Auslöser nicht"
-- L["Legendaries"] = ""
-- L["- Monk Windwalker 4P Bonus"] = ""
-- L["Nimble Brew Item Count"] = ""
-- L["- Paladin Protection 2P Bonus"] = ""
-- L["- Paladin Retribution 2P Bonus"] = ""
-- L["- Paladin T19 Retribution 4P Bonus"] = ""
L["(Pet)"] = "(Begleiter)"
-- L["Pet alive"] = ""
L["Pet Behavior"] = "Begleiterverhalten"
L["PVP Set"] = "PvP-Set"
L["PvP Talents"] = "PvP-Talente"
L["PVP Trinkets"] = "PvP-Schmuckstücke"
L["Replace all existing triggers"] = "Ersetzt alle vorhandenen Auslöser "
L["Replace Triggers"] = "Auslöser ersetzen"
L["Resources"] = "Ressourcen"
-- L["Resources and Shapeshift Form"] = ""
-- L["- Rogue Assassination/Outlaw 4P Bonus"] = ""
-- L["- Rogue Subtlety 4P Bonus"] = ""
-- L["- Rogue T19 Outlaw 4P Bonus"] = ""
L["Rooted"] = "Bewegungsunfähig"
L["Runes"] = "Runen"
-- L["- Shaman Elemental 4P Bonus"] = ""
-- L["- Shaman Enhancement 2P Bonus"] = ""
-- L["Shapeshift Form"] = ""
L["Slowed"] = "Verlangsamt"
-- L["Stagger"] = ""
-- L["Stun"] = ""
-- L["T19 Damage Trinkets"] = ""
-- L["- T19 Druid Guardian 4P Bonus"] = ""
-- L["T19 Healer Trinkets"] = ""
L["T19 Sets"] = "T19-Sets"
-- L["T19 Tank Trinkets"] = ""
L["Totem"] = "Totem"
L["Totems"] = "Totems"
L["Unknown Item"] = "Unbekannter Gegenstand"
L["Unknown Spell"] = "Unbekannter Zauber"
-- L["- Warlock Affliction 4P/Demonology 2P Bonus"] = ""
-- L["- Warlock T19 Destruction 4P Bonus"] = ""
-- L["- Warrior 2P Bonus"] = ""
-- L["- Warrior T19 Fury 2P Bonus"] = ""
L["(Water Elemental)"] = "(Wasserelementar)"



