if not(GetLocale() == "ruRU") then
    return;
end

local L = WeakAuras.L

-- Options translation
-- L["Ability Charges"] = ""
-- L["Add Triggers"] = ""
-- L["Always Active"] = ""
-- L["- Any"] = ""
-- L["Back"] = ""
-- L["Bleed"] = ""
-- L["BloodLust/Heroism"] = ""
-- L["buff"] = ""
-- L["Buff"] = ""
-- L["Buffs"] = ""
-- L["Cancel"] = ""
-- L["Cast"] = ""
-- L[" (Channeling)"] = ""
-- L["cooldown"] = ""
-- L["Cooldowns"] = ""
-- L["Crimson Vial Item Count"] = ""
-- L["- Deathknight 2P Bonus"] = ""
-- L["- Deathknight Unholy 4P Bonus"] = ""
-- L["debuff"] = ""
-- L["Debuffs"] = ""
-- L["Enchants"] = ""
-- L["General"] = ""
-- L[" (Healing received increase)"] = ""
-- L["Health"] = ""
-- L["- Holy Word: Chastise"] = ""
-- L["- Holy Word: Sanctify"] = ""
-- L["- Holy Word: Serenity"] = ""
-- L["Keeps existing triggers intact"] = ""
-- L["Legendaries"] = ""
-- L["- Monk Windwalker 4P Bonus"] = ""
-- L["Nimble Brew Item Count"] = ""
-- L["- Paladin Protection 2P Bonus"] = ""
-- L["- Paladin Retribution 2P Bonus"] = ""
-- L["- Paladin T19 Retribution 4P Bonus"] = ""
-- L["(Pet)"] = ""
-- L["Pet alive"] = ""
-- L["Pet Behavior"] = ""
-- L["PVP Set"] = ""
-- L["PvP Talents"] = ""
-- L["PVP Trinkets"] = ""
-- L["Replace all existing triggers"] = ""
-- L["Replace Triggers"] = ""
-- L["Resources"] = ""
-- L["Resources and Shapeshift Form"] = ""
-- L["- Rogue Assassination/Outlaw 4P Bonus"] = ""
-- L["- Rogue Subtlety 4P Bonus"] = ""
-- L["- Rogue T19 Outlaw 4P Bonus"] = ""
-- L["Rooted"] = ""
-- L["Runes"] = ""
-- L["- Shaman Elemental 4P Bonus"] = ""
-- L["- Shaman Enhancement 2P Bonus"] = ""
-- L["Shapeshift Form"] = ""
-- L["Slowed"] = ""
-- L["Stagger"] = ""
-- L["Stun"] = ""
-- L["T19 Damage Trinkets"] = ""
-- L["- T19 Druid Guardian 4P Bonus"] = ""
-- L["T19 Healer Trinkets"] = ""
-- L["T19 Sets"] = ""
-- L["T19 Tank Trinkets"] = ""
-- L["Totem"] = ""
-- L["Totems"] = ""
-- L["Unknown Item"] = ""
-- L["Unknown Spell"] = ""
-- L["- Warlock Affliction 4P/Demonology 2P Bonus"] = ""
-- L["- Warlock T19 Destruction 4P Bonus"] = ""
-- L["- Warrior 2P Bonus"] = ""
-- L["- Warrior T19 Fury 2P Bonus"] = ""
-- L["(Water Elemental)"] = ""



